# Generated by Django 4.1.6 on 2023-03-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('price', models.IntegerField()),
                ('content', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=500)),
                ('joined_date', models.DateField()),
            ],
        ),
    ]
