# Generated by Django 4.1.6 on 2023-03-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
