# Generated by Django 4.1.6 on 2023-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_users_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=800)),
                ('lastname', models.CharField(max_length=500)),
                ('nin', models.CharField(max_length=500)),
                ('homeaddress', models.CharField(max_length=500)),
                ('phone_no', models.CharField(max_length=500)),
                ('dob', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
