# Generated by Django 4.1.6 on 2023-03-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userinfos_delete_login_delete_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfos',
            name='dob',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='homeaddress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='nin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='phone_no',
            field=models.CharField(max_length=50),
        ),
    ]
