# Generated by Django 4.1.6 on 2023-03-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userinfos_dob_alter_userinfos_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfos',
            name='nin',
        ),
    ]
