# Generated by Django 4.1.6 on 2023-04-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_userinfos_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
